#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path of each user in /etc/passwd using a while loop and cut

while read -r line; do
    echo "$line" | cut -d':' -f1,3,6
done < /etc/passwd
