#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from apache-access.log, displaying the count of occurrences sorted in descending order

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
