#!/usr/bin/env bash
# Creates a PID file and handles multiple signals

echo "$$" > /var/run/myscript.pid

cleanup() {
    rm -f /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
