#!/usr/bin/env bash
# Init script that manages manage_my_process

case "$1" in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)" 2>/dev/null
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)" 2>/dev/null
        rm -f /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
